export const checklistTemplates: Record<string, string[]> = {
  'Presença Profissional': [
    'Criar/atualizar Google Meu Negócio',
    'Otimizar perfil completo do GMB',
    'Adicionar fotos profissionais',
    'Configurar horários de funcionamento',
    'Responder todas as avaliações existentes',
    'Criar/revisar website básico',
    'Configurar domínio e hosting',
    'Instalar certificado SSL',
    'Criar página de contacto',
    'Configurar Google Analytics',
  ],
  'Leads & Movimento': [
    'Auditoria completa das redes sociais',
    'Criar calendário de conteúdo mensal',
    'Configurar conta Business Meta',
    'Criar primeira campanha de anúncios',
    'Definir público-alvo da campanha',
    'Instalar Meta Pixel no website',
    'Criar landing page de captura',
    'Configurar formulário de leads',
    'Integrar CRM com formulários',
    'Criar relatório de acompanhamento semanal',
  ],
  'Crescimento Local': [
    'Auditoria SEO local completa',
    'Otimizar Google Meu Negócio avançado',
    'Criar estratégia de link building local',
    'Configurar schema markup',
    'Otimizar meta tags de todas as páginas',
    'Criar conteúdo SEO para páginas locais',
    'Configurar campanhas Google Ads',
    'Criar estratégia de reviews',
    'Setup relatórios mensais completos',
    'Reunião de estratégia trimestral',
    'Análise de concorrência local',
    'Plano de expansão para novos mercados',
  ],
  'Programa Aceleração Digital': [
    'Diagnóstico digital completo',
    'Definir 3 objetivos SMART para 30 dias',
    'Criar perfil profissional LinkedIn',
    'Setup básico Google Meu Negócio',
    'Criar conta Instagram Business',
    'Publicar primeiros 5 posts',
    'Responder comentários e mensagens',
    'Primeira reunião de acompanhamento',
  ],
}
